import { Component,OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder,ReactiveFormsModule,Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { ApiService } from '../core/api.service';
import { AuthService } from '../core/auth.service';
import { Device,DeviceRequest,ServiceUnit,User } from '../core/models';

@Component({standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink],template:`
<div class="page-title"><div><small>INVENTAR</small><h2>Uređaji</h2><p>Serveri, mrežna i skladišna infrastruktura.</p></div><button *ngIf="auth.isAdmin()" class="primary" (click)="open()">+ Novi uređaj</button></div>
<div class="panel"><table><thead><tr><th>Naziv / hostname</th><th>Tip</th><th>IP adresa</th><th>Servisna jedinica</th><th>Odgovorna osoba</th><th>Status</th><th></th></tr></thead><tbody><tr *ngFor="let d of devices"><td><a class="table-link" [routerLink]="['/devices',d.id,'software']"><b>{{d.name}}</b><small>{{d.hostname||'—'}}</small></a></td><td>{{label(d.deviceType)}}</td><td class="mono">{{d.ipAddress||'—'}}</td><td>{{d.serviceUnitName}}</td><td>{{d.responsibleUserName}}</td><td><span class="badge" [class.success]="d.status==='ACTIVE'">{{label(d.status)}}</span></td><td class="actions"><a class="button-link" [routerLink]="['/devices',d.id,'software']">Softver</a><button *ngIf="auth.isAdmin()" (click)="open(d)">Izmeni</button><button *ngIf="auth.isAdmin()" class="danger-text" (click)="remove(d)">Obriši</button></td></tr><tr *ngIf="!devices.length"><td colspan="7" class="empty">Nema evidentiranih uređaja.</td></tr></tbody></table></div>
<div class="modal-backdrop" *ngIf="editing"><form class="modal" [formGroup]="form" (ngSubmit)="save()"><div class="modal-head"><div><small>INVENTAR</small><h3>{{selected?'Izmena uređaja':'Novi uređaj'}}</h3></div><button type="button" (click)="close()">×</button></div><div class="form-grid"><label class="wide">Naziv<input formControlName="name"></label><label>Hostname<input formControlName="hostname"></label><label>IP adresa<input formControlName="ipAddress"></label><label>Serijski broj<input formControlName="serialNumber"></label><label>Proizvođač<input formControlName="manufacturer"></label><label>Model<input formControlName="model"></label><label>Tip<select formControlName="deviceType"><option value="PHYSICAL_SERVER">Fizički server</option><option value="VIRTUAL_SERVER">Virtuelni server</option><option value="NETWORK_DEVICE">Mrežni uređaj</option><option value="STORAGE">Storage</option><option value="OTHER">Ostalo</option></select></label><label>Status<select formControlName="status"><option value="ACTIVE">Aktivan</option><option value="INACTIVE">Neaktivan</option><option value="MAINTENANCE">Održavanje</option><option value="RETIRED">Povučen</option></select></label><label>Servisna jedinica<select formControlName="serviceUnitId" (change)="filterUsers()"><option [value]="0">Izaberite</option><option *ngFor="let s of units" [value]="s.id">{{s.name}}</option></select></label><label>Odgovorna osoba<select formControlName="responsibleUserId"><option [value]="0">Izaberite</option><option *ngFor="let u of availableUsers" [value]="u.id">{{u.firstName}} {{u.lastName}}</option></select></label></div><div class="error" *ngIf="error">{{error}}</div><div class="modal-actions"><button type="button" (click)="close()">Otkaži</button><button class="primary" [disabled]="form.invalid||saving">{{saving?'Čuvanje...':'Sačuvaj'}}</button></div></form></div>`})
export class DevicesComponent implements OnInit {
 devices:Device[]=[]; units:ServiceUnit[]=[]; users:User[]=[]; availableUsers:User[]=[]; editing=false; selected:Device|null=null; saving=false; error='';
 form=this.fb.nonNullable.group({serviceUnitId:[0,[Validators.min(1)]],responsibleUserId:[0,[Validators.min(1)]],name:['',[Validators.required]],hostname:[''],ipAddress:[''],serialNumber:[''],manufacturer:[''],model:[''],deviceType:['PHYSICAL_SERVER',[Validators.required]],status:['ACTIVE',[Validators.required]]});
 constructor(private api:ApiService,public auth:AuthService,private fb:FormBuilder){}
 ngOnInit():void{this.load();}
 load():void{if(!this.auth.isAdmin()){this.api.devices().subscribe(v=>this.devices=v);return;}forkJoin({devices:this.api.devices(),units:this.api.serviceUnits(),users:this.api.users()}).subscribe(v=>{this.devices=v.devices;this.units=v.units;this.users=v.users.filter(u=>u.active);});}
 open(device?:Device):void{this.selected=device??null;this.error='';this.form.reset(device?{serviceUnitId:device.serviceUnitId,responsibleUserId:device.responsibleUserId,name:device.name,hostname:device.hostname??'',ipAddress:device.ipAddress??'',serialNumber:device.serialNumber??'',manufacturer:device.manufacturer??'',model:device.model??'',deviceType:device.deviceType,status:device.status}:{serviceUnitId:0,responsibleUserId:0,name:'',hostname:'',ipAddress:'',serialNumber:'',manufacturer:'',model:'',deviceType:'PHYSICAL_SERVER',status:'ACTIVE'});this.filterUsers(false);this.editing=true;}
 filterUsers(clear=true):void{const id=Number(this.form.controls.serviceUnitId.value);this.availableUsers=this.users.filter(u=>u.serviceUnitId===id);if(clear&&!this.availableUsers.some(u=>u.id===Number(this.form.controls.responsibleUserId.value)))this.form.controls.responsibleUserId.setValue(0);}
 close():void{this.editing=false;this.selected=null;}
 save():void{if(this.form.invalid)return;this.saving=true;const raw=this.form.getRawValue();const value:DeviceRequest={...raw,serviceUnitId:Number(raw.serviceUnitId),responsibleUserId:Number(raw.responsibleUserId),hostname:raw.hostname||null,ipAddress:raw.ipAddress||null,serialNumber:raw.serialNumber||null,manufacturer:raw.manufacturer||null,model:raw.model||null};const request=this.selected?this.api.updateDevice(this.selected.id,value):this.api.createDevice(value);request.subscribe({next:()=>{this.saving=false;this.close();this.load();},error:e=>{this.saving=false;this.error=e.error?.message??'Uređaj nije sačuvan.';}});}
 remove(device:Device):void{if(!confirm(`Obrisati uređaj „${device.name}“?`))return;this.api.deleteDevice(device.id).subscribe({next:()=>this.load(),error:e=>alert(e.error?.message??'Brisanje nije uspelo.')});}
 label(v:string):string{return v.replaceAll('_',' ');}
}
