import { Component,OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder,ReactiveFormsModule,Validators } from '@angular/forms';
import { ActivatedRoute,RouterLink } from '@angular/router'; import { forkJoin } from 'rxjs';
import { ApiService } from '../core/api.service'; import { AuthService } from '../core/auth.service';
import { Device,Installation,License,Software } from '../core/models';

@Component({standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink],template:`
<div class="page-title"><div><a routerLink="/devices" class="back">← Uređaji</a><small>INSTALIRANI SOFTVER</small><h2>{{device?.name||'Uređaj'}}</h2><p>{{device?.hostname}} · {{device?.ipAddress}}</p></div><button *ngIf="auth.isAdmin()" class="primary" (click)="editing=true">+ Dodaj instalaciju</button></div>
<div class="panel"><table><thead><tr><th>Softver</th><th>Verzija</th><th>Datum instalacije</th><th>Licenca</th><th>Status</th><th *ngIf="auth.isAdmin()"></th></tr></thead><tbody><tr *ngFor="let i of items"><td><b>{{i.softwareName}}</b></td><td>{{i.installedVersion||'—'}}</td><td>{{i.installationDate?(i.installationDate|date:'dd.MM.yyyy'):'—'}}</td><td>{{i.licenseId?'#'+i.licenseId:'Bez licence'}}</td><td><span class="badge" [class.success]="i.status==='INSTALLED'">{{i.status}}</span></td><td *ngIf="auth.isAdmin()" class="actions"><button class="danger-text" (click)="remove(i)">Ukloni</button></td></tr><tr *ngIf="!items.length"><td colspan="6" class="empty">Na uređaju nema evidentiranog softvera.</td></tr></tbody></table></div>
<div class="modal-backdrop" *ngIf="editing"><form class="modal compact" [formGroup]="form" (ngSubmit)="save()"><div class="modal-head"><div><small>INSTALACIJA</small><h3>Dodaj softver</h3></div><button type="button" (click)="editing=false">×</button></div><label>Softver<select formControlName="softwareId" (change)="filterLicenses()"><option [value]="0">Izaberite</option><option *ngFor="let s of software" [value]="s.id">{{s.name}} {{s.version}}</option></select></label><label>Licenca<select formControlName="licenseId"><option [value]="0">Bez licence</option><option *ngFor="let l of availableLicenses" [value]="l.id">#{{l.id}} · ističe {{l.endDate|date:'dd.MM.yyyy'}}</option></select></label><div class="form-grid"><label>Instalirana verzija<input formControlName="installedVersion"></label><label>Datum instalacije<input type="date" formControlName="installationDate"></label></div><div class="error" *ngIf="error">{{error}}</div><div class="modal-actions"><button type="button" (click)="editing=false">Otkaži</button><button class="primary" [disabled]="form.invalid||saving">Sačuvaj</button></div></form></div>`})
export class InstallationsComponent implements OnInit {
 deviceId=Number(this.route.snapshot.paramMap.get('id'));device:Device|null=null;items:Installation[]=[];software:Software[]=[];licenses:License[]=[];availableLicenses:License[]=[];editing=false;saving=false;error='';
 form=this.fb.nonNullable.group({softwareId:[0,[Validators.min(1)]],licenseId:[0],installationDate:[new Date().toISOString().slice(0,10)],installedVersion:['']});
 constructor(private route:ActivatedRoute,private api:ApiService,public auth:AuthService,private fb:FormBuilder){}
 ngOnInit():void{this.load();forkJoin({software:this.api.software(),licenses:this.api.licenses()}).subscribe(v=>{this.software=v.software;this.licenses=v.licenses;});}
 load():void{forkJoin({device:this.api.device(this.deviceId),items:this.api.installations(this.deviceId)}).subscribe(v=>{this.device=v.device;this.items=v.items;});}
 filterLicenses():void{const id=Number(this.form.controls.softwareId.value);this.availableLicenses=this.licenses.filter(l=>l.softwareId===id&&l.computedStatus!=='EXPIRED');this.form.controls.licenseId.setValue(0);}
 save():void{if(this.form.invalid)return;this.saving=true;const v=this.form.getRawValue();this.api.createInstallation({deviceId:this.deviceId,softwareId:Number(v.softwareId),licenseId:Number(v.licenseId)||null,installationDate:v.installationDate,installedVersion:v.installedVersion,status:'INSTALLED'}).subscribe({next:()=>{this.saving=false;this.editing=false;this.form.reset({softwareId:0,licenseId:0,installationDate:new Date().toISOString().slice(0,10),installedVersion:''});this.load();},error:e=>{this.saving=false;this.error=e.error?.message??'Instalacija nije sačuvana.';}});}
 remove(item:Installation):void{if(confirm(`Ukloniti „${item.softwareName}“ sa uređaja?`))this.api.deleteInstallation(item.id).subscribe({next:()=>this.load(),error:e=>alert(e.error?.message)});}
}
