import { Component,OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder,ReactiveFormsModule,Validators } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { ApiService } from '../core/api.service'; import { AuthService } from '../core/auth.service';
import { License,Renewal,Software } from '../core/models';

@Component({standalone:true,imports:[CommonModule,ReactiveFormsModule],template:`
<div class="page-title">
 <div><small>USKLAĐENOST</small><h2>Softverske licence</h2><p>Važenje i iskorišćenost licenciranog softvera.</p></div>
 <button *ngIf="auth.isAdmin()" class="primary" (click)="openEditor()">+ Nova licenca</button>
</div>
<div class="panel"><table><thead><tr><th>Softver</th><th>Tip licence</th><th>Početak</th><th>Ističe</th><th>Količina</th><th>Status</th><th></th></tr></thead><tbody>
 <tr *ngFor="let l of licenses"><td><b>{{l.softwareName}}</b><small>{{l.notes||'—'}}</small></td><td>{{l.licenseType}}</td><td>{{l.startDate|date:'dd.MM.yyyy'}}</td><td>{{l.endDate?(l.endDate|date:'dd.MM.yyyy'):'Trajna'}}</td><td>{{l.quantity}}</td><td><span class="badge" [class.success]="l.computedStatus==='ACTIVE'||l.computedStatus==='PERPETUAL'" [class.warning]="l.computedStatus==='EXPIRING_SOON'" [class.danger]="l.computedStatus==='EXPIRED'">{{label(l.computedStatus)}}</span></td><td class="actions"><button *ngIf="l.licenseType!=='PERPETUAL'" (click)="openRenewal(l)">Obnovi</button><button *ngIf="auth.isAdmin()" (click)="openEditor(l)">Izmeni</button><button *ngIf="auth.isAdmin()" class="danger-text" (click)="remove(l)">Obriši</button></td></tr>
 <tr *ngIf="!licenses.length"><td colspan="7" class="empty">Nema evidentiranih licenci.</td></tr>
</tbody></table></div>

<div class="modal-backdrop" *ngIf="editorOpen"><form class="modal" [formGroup]="licenseForm" (ngSubmit)="saveLicense()"><div class="modal-head"><div><small>LICENCA</small><h3>{{editedLicense?'Izmena licence':'Nova licenca'}}</h3></div><button type="button" (click)="closeEditor()">×</button></div><div class="form-grid"><label class="wide">Softver<select formControlName="softwareId"><option [value]="0">Izaberite softver</option><option *ngFor="let s of software" [value]="s.id">{{s.name}} {{s.version}}</option></select></label><label>Tip<select formControlName="licenseType"><option value="SUBSCRIPTION">Pretplata</option><option value="PERPETUAL">Trajna</option><option value="TRIAL">Probna</option></select></label><label>Količina<input type="number" min="1" formControlName="quantity"></label><label>Početni datum<input type="date" formControlName="startDate"></label><label>Datum isteka<input type="date" formControlName="endDate" [disabled]="!!editedLicense"></label><label>Licencni ključ<input formControlName="licenseKey"></label><label>Cena<input type="number" min="0" step="0.01" formControlName="purchasePrice"></label><label class="wide">Napomena<textarea rows="3" formControlName="notes"></textarea></label></div><p class="form-hint" *ngIf="editedLicense">Datum isteka menja se isključivo kroz operaciju „Obnovi“.</p><div class="error" *ngIf="error">{{error}}</div><div class="modal-actions"><button type="button" (click)="closeEditor()">Otkaži</button><button class="primary" [disabled]="licenseForm.invalid||saving">Sačuvaj</button></div></form></div>

<div class="modal-backdrop" *ngIf="renewedLicense"><form class="modal compact" [formGroup]="renewalForm" (ngSubmit)="renew()"><div class="modal-head"><div><small>OBNOVA LICENCE</small><h3>{{renewedLicense.softwareName}}</h3></div><button type="button" (click)="closeRenewal()">×</button></div><div class="renewal-current"><span>Trenutni datum isteka</span><b>{{renewedLicense.endDate|date:'dd.MM.yyyy'}}</b></div><label>Novi datum isteka<input type="date" formControlName="newEndDate" [min]="minimumDate"></label><label>Napomena<textarea rows="3" formControlName="note" placeholder="Broj ugovora ili razlog obnove"></textarea></label><div class="error" *ngIf="error">{{error}}</div><div class="modal-actions"><button type="button" (click)="closeRenewal()">Otkaži</button><button class="primary" [disabled]="renewalForm.invalid||saving">Obnovi licencu</button></div><div class="history" *ngIf="history.length"><h4>Prethodne obnove</h4><div *ngFor="let item of history"><b>{{item.previousEndDate|date:'dd.MM.yyyy'}} → {{item.newEndDate|date:'dd.MM.yyyy'}}</b><small>{{item.renewedByName}} · {{item.renewedAt|date:'dd.MM.yyyy HH:mm'}}</small></div></div></form></div>`})
export class LicensesComponent implements OnInit {
 licenses:License[]=[];software:Software[]=[];editedLicense:License|null=null;renewedLicense:License|null=null;editorOpen=false;history:Renewal[]=[];saving=false;error='';minimumDate=new Date(Date.now()+86400000).toISOString().slice(0,10);
 licenseForm=this.fb.nonNullable.group({softwareId:[0,[Validators.min(1)]],licenseKey:[''],licenseType:['SUBSCRIPTION',[Validators.required]],startDate:['',[Validators.required]],endDate:[''],quantity:[1,[Validators.min(1)]],purchasePrice:[0],notes:['']});
 renewalForm=this.fb.nonNullable.group({newEndDate:['',[Validators.required]],note:['']});
 constructor(private api:ApiService,public auth:AuthService,private fb:FormBuilder){}
 ngOnInit():void{this.load();}
 load():void{forkJoin({licenses:this.api.licenses(),software:this.api.software()}).subscribe(v=>{this.licenses=v.licenses;this.software=v.software;});}
 openEditor(item?:License):void{this.editedLicense=item??null;this.error='';this.licenseForm.reset(item?{softwareId:item.softwareId,licenseKey:item.licenseKey??'',licenseType:item.licenseType,startDate:item.startDate,endDate:item.endDate??'',quantity:item.quantity,purchasePrice:item.purchasePrice??0,notes:item.notes??''}:{softwareId:0,licenseKey:'',licenseType:'SUBSCRIPTION',startDate:new Date().toISOString().slice(0,10),endDate:'',quantity:1,purchasePrice:0,notes:''});this.editorOpen=true;}
 closeEditor():void{this.editorOpen=false;this.editedLicense=null;}
 saveLicense():void{if(this.licenseForm.invalid)return;this.saving=true;const v=this.licenseForm.getRawValue();const endDate=v.licenseType==='PERPETUAL'?null:((this.editedLicense?.endDate??v.endDate)||null);this.api.saveLicense({softwareId:Number(v.softwareId),licenseKey:v.licenseKey||null,licenseType:v.licenseType,startDate:v.startDate,endDate,quantity:Number(v.quantity),purchasePrice:Number(v.purchasePrice)||null,notes:v.notes},this.editedLicense?.id).subscribe({next:()=>{this.saving=false;this.closeEditor();this.load();},error:e=>{this.saving=false;this.error=e.error?.message??'Licenca nije sačuvana.';}});}
 remove(item:License):void{if(confirm(`Obrisati licencu za „${item.softwareName}“?`))this.api.deleteLicense(item.id).subscribe({next:()=>this.load(),error:e=>alert(e.error?.message??'Brisanje nije uspelo.')});}
 openRenewal(item:License):void{this.renewedLicense=item;this.error='';this.history=[];this.renewalForm.reset({newEndDate:'',note:''});this.api.renewalHistory(item.id).subscribe({next:v=>this.history=v,error:e=>this.error=e.status===403?'Niste odgovorna osoba za uređaj koji koristi ovu licencu.':''});}
 closeRenewal():void{this.renewedLicense=null;this.history=[];}
 renew():void{if(!this.renewedLicense||this.renewalForm.invalid)return;this.saving=true;const v=this.renewalForm.getRawValue();this.api.renewLicense(this.renewedLicense.id,v.newEndDate,v.note).subscribe({next:()=>{this.saving=false;this.closeRenewal();this.load();},error:e=>{this.saving=false;this.error=e.error?.message??'Obnova nije uspela.';}});}
 label(v:string):string{return v.replaceAll('_',' ');}
}
