import { Component,OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder,ReactiveFormsModule,Validators } from '@angular/forms';
import { ApiService } from '../core/api.service'; import { Software } from '../core/models';

@Component({standalone:true,imports:[CommonModule,ReactiveFormsModule],template:`
<div class="page-title"><div><small>KATALOG</small><h2>Softver</h2><p>Proizvodi i verzije dostupni za instaliranje na uređaje.</p></div><button class="primary" (click)="open()">+ Novi softver</button></div>
<div class="panel"><table><thead><tr><th>Naziv</th><th>Proizvođač</th><th>Verzija</th><th>Kategorija</th><th></th></tr></thead><tbody><tr *ngFor="let s of items"><td><b>{{s.name}}</b><small>{{s.description||'—'}}</small></td><td>{{s.vendor}}</td><td>{{s.version}}</td><td><span class="badge">{{label(s.softwareType)}}</span></td><td class="actions"><button (click)="open(s)">Izmeni</button><button class="danger-text" (click)="remove(s)">Obriši</button></td></tr><tr *ngIf="!items.length"><td colspan="5" class="empty">Katalog softvera je prazan.</td></tr></tbody></table></div>
<div class="modal-backdrop" *ngIf="editing"><form class="modal compact" [formGroup]="form" (ngSubmit)="save()"><div class="modal-head"><div><small>KATALOG</small><h3>{{selected?'Izmena softvera':'Novi softver'}}</h3></div><button type="button" (click)="close()">×</button></div><div class="form-grid"><label>Naziv<input formControlName="name"></label><label>Proizvođač<input formControlName="vendor"></label><label>Verzija<input formControlName="version"></label><label>Kategorija<select formControlName="softwareType"><option value="OPERATING_SYSTEM">Operativni sistem</option><option value="DATABASE">Baza podataka</option><option value="APPLICATION">Aplikacija</option><option value="SECURITY">Bezbednost</option><option value="MONITORING">Monitoring</option><option value="OTHER">Ostalo</option></select></label><label class="wide">Opis<textarea rows="3" formControlName="description"></textarea></label></div><div class="error" *ngIf="error">{{error}}</div><div class="modal-actions"><button type="button" (click)="close()">Otkaži</button><button class="primary" [disabled]="form.invalid||saving">Sačuvaj</button></div></form></div>`})
export class SoftwareComponent implements OnInit {
 items:Software[]=[];selected:Software|null=null;editing=false;saving=false;error='';form=this.fb.nonNullable.group({name:['',[Validators.required]],vendor:['',[Validators.required]],version:['',[Validators.required]],softwareType:['APPLICATION',[Validators.required]],description:['']});
 constructor(private api:ApiService,private fb:FormBuilder){}ngOnInit():void{this.load();}load():void{this.api.software().subscribe(v=>this.items=v);}
 open(item?:Software):void{this.selected=item??null;this.form.reset(item?{name:item.name,vendor:item.vendor,version:item.version,softwareType:item.softwareType,description:item.description??''}:{name:'',vendor:'',version:'',softwareType:'APPLICATION',description:''});this.error='';this.editing=true;}close():void{this.editing=false;this.selected=null;}
 save():void{if(this.form.invalid)return;this.saving=true;this.api.saveSoftware(this.form.getRawValue(),this.selected?.id).subscribe({next:()=>{this.saving=false;this.close();this.load();},error:e=>{this.saving=false;this.error=e.error?.message??'Čuvanje nije uspelo.';}});}
 remove(item:Software):void{if(confirm(`Obrisati softver „${item.name}“?`))this.api.deleteSoftware(item.id).subscribe({next:()=>this.load(),error:e=>alert(e.error?.message??'Brisanje nije uspelo.')});}
 label(value:string):string{return value.replaceAll('_',' ');}
}
