import { Component,OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder,ReactiveFormsModule,Validators } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { ApiService } from '../core/api.service';
import { Role,ServiceUnit,User,UserCreateRequest,UserUpdateRequest } from '../core/models';

@Component({standalone:true,imports:[CommonModule,ReactiveFormsModule],template:`
<div class="page-title"><div><small>ADMINISTRACIJA</small><h2>Korisnici</h2><p>Nalozi, uloge i pripadnost servisnim jedinicama.</p></div><button class="primary" (click)="open()">+ Novi korisnik</button></div>
<div class="panel"><table><thead><tr><th>Korisnik</th><th>Email</th><th>Servisna jedinica</th><th>Uloga</th><th>Status</th><th></th></tr></thead><tbody><tr *ngFor="let u of users"><td><b>{{u.firstName}} {{u.lastName}}</b><small>@{{u.username}}</small></td><td>{{u.email}}</td><td>{{u.serviceUnitName}}</td><td><span class="badge">{{u.role}}</span></td><td><span class="badge" [class.success]="u.active" [class.danger]="!u.active">{{u.active?'Aktivan':'Neaktivan'}}</span></td><td class="actions"><button (click)="open(u)">Izmeni</button><button class="danger-text" (click)="remove(u)">Obriši</button></td></tr><tr *ngIf="!users.length"><td colspan="6" class="empty">Nema korisnika.</td></tr></tbody></table></div>
<div class="modal-backdrop" *ngIf="editing"><form class="modal compact" [formGroup]="form" (ngSubmit)="save()"><div class="modal-head"><div><small>ADMINISTRACIJA</small><h3>{{selected?'Izmena korisnika':'Novi korisnik'}}</h3></div><button type="button" (click)="close()">×</button></div><div class="form-grid"><label>Ime<input formControlName="firstName"></label><label>Prezime<input formControlName="lastName"></label><label>Korisničko ime<input formControlName="username"></label><label>Email<input type="email" formControlName="email"></label><label class="wide" *ngIf="!selected">Početna lozinka<input type="password" formControlName="password"><small>Najmanje osam karaktera</small></label><label>Servisna jedinica<select formControlName="serviceUnitId"><option [value]="0">Izaberite</option><option *ngFor="let s of units" [value]="s.id">{{s.name}}</option></select></label><label>Uloga<select formControlName="role"><option value="USER">Korisnik</option><option value="ADMIN">Administrator</option></select></label><label class="check wide" *ngIf="selected"><input type="checkbox" formControlName="active"> Aktivan nalog</label></div><div class="error" *ngIf="error">{{error}}</div><div class="modal-actions"><button type="button" (click)="close()">Otkaži</button><button class="primary" [disabled]="form.invalid||saving">{{saving?'Čuvanje...':'Sačuvaj'}}</button></div></form></div>`})
export class UsersComponent implements OnInit {
 users:User[]=[];units:ServiceUnit[]=[];editing=false;selected:User|null=null;saving=false;error='';
 form=this.fb.nonNullable.group({serviceUnitId:[0,[Validators.min(1)]],username:['',[Validators.required,Validators.minLength(3)]],password:['',[Validators.minLength(8)]],firstName:['',[Validators.required]],lastName:['',[Validators.required]],email:['',[Validators.required,Validators.email]],role:['USER' as Role,[Validators.required]],active:[true]});
 constructor(private api:ApiService,private fb:FormBuilder){}
 ngOnInit():void{this.load();}
 load():void{forkJoin({users:this.api.users(),units:this.api.serviceUnits()}).subscribe(v=>{this.users=v.users;this.units=v.units;});}
 open(user?:User):void{this.selected=user??null;this.error='';this.form.reset(user?{serviceUnitId:user.serviceUnitId,username:user.username,password:'',firstName:user.firstName,lastName:user.lastName,email:user.email,role:user.role,active:user.active}:{serviceUnitId:0,username:'',password:'',firstName:'',lastName:'',email:'',role:'USER',active:true});if(user)this.form.controls.password.clearValidators();else this.form.controls.password.setValidators([Validators.required,Validators.minLength(8)]);this.form.controls.password.updateValueAndValidity();this.editing=true;}
 close():void{this.editing=false;this.selected=null;}
 save():void{if(this.form.invalid)return;this.saving=true;const raw=this.form.getRawValue();const request=this.selected?this.api.updateUser(this.selected.id,{serviceUnitId:Number(raw.serviceUnitId),username:raw.username,firstName:raw.firstName,lastName:raw.lastName,email:raw.email,role:raw.role,active:raw.active} satisfies UserUpdateRequest):this.api.createUser({serviceUnitId:Number(raw.serviceUnitId),username:raw.username,password:raw.password,firstName:raw.firstName,lastName:raw.lastName,email:raw.email,role:raw.role} satisfies UserCreateRequest);request.subscribe({next:()=>{this.saving=false;this.close();this.load();},error:e=>{this.saving=false;this.error=e.error?.message??'Korisnik nije sačuvan.';}});}
 remove(user:User):void{if(!confirm(`Obrisati korisnika „${user.username}“? Ako ima povezane podatke, deaktivirajte ga.`))return;this.api.deleteUser(user.id).subscribe({next:()=>this.load(),error:e=>alert(e.error?.message??'Brisanje nije uspelo.')});}
}
